export const orgChartData = [
  {
    id: 1,
    firstName: 'Amir',
    middleName: '',
    lastName: 'Suliman',
    tittle: 'Front-end Developer',
    gender: 'Male',
    marritialStatus: 'Single',
    paymentSchedule: 'Biweekly',
    employmentType: 'Freelance',
    profilePictureUrl:
      'https://wb-uploads.s3.amazonaws.com/public/1736934151835-about-us-hero-side-img.png',
    linkedin: 'linkedin.com/profile',
    facebook: null,
    instagram: null,
    website: null,
    email: 'amirsuliman10101@gmail.com',
    phoneNumber: '03478663296',
    workPhone: '121212121',
    reportingManagerId: 10,
    departmentId: 5,
    salary: 2444440,
    locationId: 1,
    effectiveDate: '2025-01-10T00:00:00.000Z',
    hireDate: '2025-01-09T00:00:00.000Z',
    birthday: '2025-01-09T00:00:00.000Z',
    userId: 4,
    manager: {
      firstName: 'testing',
      lastName: 'user',
      department: {
        id: 1,
        name: 'Engineering',
        employeeId: '',
      },
      location: {
        id: 1,
        street1: '1365',
        street2: null,
        zipCode: 23000,
        city: 'Prishtine',
        country: 'Albania',
        state: 'Kosovo',
      },
    },
    location: {
      country: 'Albania',
      state: 'Kosovo',
      city: 'Prishtine',
      zipCode: 23000,
      id: 1,
      street1: '1365',
      street2: null,
    },
    department: {
      id: 1,
      name: 'Finance',
    },
    openPositions: [],
    parentId: null,
  },
  {
    id: 2,
    firstName: 'Amir',
    middleName: '',
    lastName: 'Suliman',
    tittle: 'Front-end Developer',
    gender: 'Male',
    marritialStatus: 'Single',
    paymentSchedule: 'Biweekly',
    employmentType: 'Freelance',
    profilePictureUrl:
      'https://wb-uploads.s3.amazonaws.com/public/1736934151835-about-us-hero-side-img.png',
    linkedin: 'linkedin.com/profile',
    facebook: null,
    instagram: null,
    website: null,
    email: 'amirsuliman10101@gmail.com',
    phoneNumber: '03478663296',
    workPhone: '121212121',
    reportingManagerId: 10,
    departmentId: 5,
    salary: 2444440,
    locationId: 1,
    effectiveDate: '2025-01-10T00:00:00.000Z',
    hireDate: '2025-01-09T00:00:00.000Z',
    birthday: '2025-01-09T00:00:00.000Z',
    userId: 4,
    manager: {
      firstName: 'testing',
      lastName: 'user',
      department: {
        id: 1,
        name: 'Engineering',
        employeeId: '',
      },
      location: {
        id: 1,
        street1: '1365',
        street2: null,
        zipCode: 23000,
        city: 'Prishtine',
        country: 'Albania',
        state: 'Kosovo',
      },
    },
    location: {
      country: 'Albania',
      state: 'Kosovo',
      city: 'Prishtine',
      zipCode: 23000,
      id: 1,
      street1: '1365',
      street2: null,
    },
    department: {
      id: 1,
      name: 'Finance',
    },
    openPositions: [],
    parentId: 1,
  },
  {
    id: 3,
    firstName: 'Amir',
    middleName: '',
    lastName: 'Suliman',
    tittle: 'Front-end Developer',
    gender: 'Male',
    marritialStatus: 'Single',
    paymentSchedule: 'Biweekly',
    employmentType: 'Freelance',
    profilePictureUrl:
      'https://wb-uploads.s3.amazonaws.com/public/1736934151835-about-us-hero-side-img.png',
    linkedin: 'linkedin.com/profile',
    facebook: null,
    instagram: null,
    website: null,
    email: 'amirsuliman10101@gmail.com',
    phoneNumber: '03478663296',
    workPhone: '121212121',
    reportingManagerId: 10,
    departmentId: 5,
    salary: 2444440,
    locationId: 1,
    effectiveDate: '2025-01-10T00:00:00.000Z',
    hireDate: '2025-01-09T00:00:00.000Z',
    birthday: '2025-01-09T00:00:00.000Z',
    userId: 4,
    manager: {
      firstName: 'testing',
      lastName: 'user',
      department: {
        id: 1,
        name: 'Engineering',
        employeeId: '',
      },
      location: {
        id: 1,
        street1: '1365',
        street2: null,
        zipCode: 23000,
        city: 'Prishtine',
        country: 'Albania',
        state: 'Kosovo',
      },
    },
    location: {
      country: 'Albania',
      state: 'Kosovo',
      city: 'Prishtine',
      zipCode: 23000,
      id: 1,
      street1: '1365',
      street2: null,
    },
    department: {
      id: 1,
      name: 'Finance',
    },
    openPositions: [],
    parentId: 2,
  },
  {
    id: 4,
    firstName: 'Amir',
    middleName: '',
    lastName: 'Suliman',
    tittle: 'Front-end Developer',
    gender: 'Male',
    marritialStatus: 'Single',
    paymentSchedule: 'Biweekly',
    employmentType: 'Freelance',
    profilePictureUrl:
      'https://wb-uploads.s3.amazonaws.com/public/1736934151835-about-us-hero-side-img.png',
    linkedin: 'linkedin.com/profile',
    facebook: null,
    instagram: null,
    website: null,
    email: 'amirsuliman10101@gmail.com',
    phoneNumber: '03478663296',
    workPhone: '121212121',
    reportingManagerId: 10,
    departmentId: 5,
    salary: 2444440,
    locationId: 1,
    effectiveDate: '2025-01-10T00:00:00.000Z',
    hireDate: '2025-01-09T00:00:00.000Z',
    birthday: '2025-01-09T00:00:00.000Z',
    userId: 4,
    manager: {
      firstName: 'testing',
      lastName: 'user',
      department: {
        id: 1,
        name: 'Engineering',
        employeeId: '',
      },
      location: {
        id: 1,
        street1: '1365',
        street2: null,
        zipCode: 23000,
        city: 'Prishtine',
        country: 'Albania',
        state: 'Kosovo',
      },
    },
    location: {
      country: 'Albania',
      state: 'Kosovo',
      city: 'Prishtine',
      zipCode: 23000,
      id: 1,
      street1: '1365',
      street2: null,
    },
    department: {
      id: 1,
      name: 'Finance',
    },
    openPositions: [],
    parentId: 2,
  },
];
