export const orgChartData = [
  {
    id: 1,
    firstName: 'Amir',
    middleName: '',
    lastName: 'Suliman',
    tittle: 'Front-end Developer',
    gender: 'Male',
    marritialStatus: 'Single',
    paymentSchedule: 'Biweekly',
    employmentType: 'Freelance',
    profilePictureUrl:
      'https://wb-uploads.s3.amazonaws.com/public/1736934151835-about-us-hero-side-img.png',
    linkedin: 'linkedin.com/profile',
    facebook: null,
    instagram: null,
    website: null,
    email: 'amirsuliman10101@gmail.com',
    phoneNumber: '03478663296',
    workPhone: '121212121',
    reportingManagerId: 10,
    departmentId: 5,
    salary: 2444440,
    locationId: 1,
    effectiveDate: '2025-01-10T00:00:00.000Z',
    hireDate: '2025-01-09T00:00:00.000Z',
    birthday: '2025-01-09T00:00:00.000Z',
    userId: 4,
    manager: {
      firstName: 'testing',
      lastName: 'user',
      department: {
        id: 1,
        name: 'Engineering',
        employeeId: '',
      },
      location: {
        id: 1,
        street1: '1365',
        street2: null,
        zipCode: 23000,
        city: 'Prishtine',
        country: 'Albania',
        state: 'Kosovo',
      },
    },
    location: {
      country: 'Albania',
      state: 'Kosovo',
      city: 'Prishtine',
      zipCode: 23000,
      id: 1,
      street1: '1365',
      street2: null,
    },
    department: {
      id: 1,
      name: 'Finance',
    },
    openPositions: [
      {
        location: {
          country: 'Albania',
          state: 'Kosovo',
          city: 'Prishtine',
          zipCode: 23000,
          id: 1,
          street1: '1365',
          street2: null,
        },
        department: {
          id: 1,
          name: 'Finance',
        },
        salary: 45000,
        tittle: 'Sales Representative',
      },
    ],
    parentId: null,
  },
  {
    id: 2,
    firstName: 'Amir',
    middleName: '',
    lastName: 'Suliman',
    tittle: 'Front-end Developer',
    gender: 'Male',
    marritialStatus: 'Single',
    paymentSchedule: 'Biweekly',
    employmentType: 'Freelance',
    profilePictureUrl:
      'https://wb-uploads.s3.amazonaws.com/public/1736934151835-about-us-hero-side-img.png',
    linkedin: 'linkedin.com/profile',
    facebook: null,
    instagram: null,
    website: null,
    email: 'amirsuliman10101@gmail.com',
    phoneNumber: '03478663296',
    workPhone: '121212121',
    reportingManagerId: 10,
    departmentId: 5,
    salary: 2444440,
    locationId: 1,
    effectiveDate: '2025-01-10T00:00:00.000Z',
    hireDate: '2025-01-09T00:00:00.000Z',
    birthday: '2025-01-09T00:00:00.000Z',
    userId: 4,
    manager: {
      firstName: 'testing',
      lastName: 'user',
      department: {
        id: 1,
        name: 'Engineering',
        employeeId: '',
      },
      location: {
        id: 1,
        street1: '1365',
        street2: null,
        zipCode: 23000,
        city: 'Prishtine',
        country: 'Albania',
        state: 'Kosovo',
      },
    },
    location: {
      country: 'Albania',
      state: 'Kosovo',
      city: 'Prishtine',
      zipCode: 23000,
      id: 1,
      street1: '1365',
      street2: null,
    },
    department: {
      id: 1,
      name: 'Finance',
    },
    openPositions: [],
    parentId: 1,
  },
  {
    id: 3,
    firstName: 'Amir',
    middleName: '',
    lastName: 'Suliman',
    tittle: 'Front-end Developer',
    gender: 'Male',
    marritialStatus: 'Single',
    paymentSchedule: 'Biweekly',
    employmentType: 'Freelance',
    profilePictureUrl:
      'https://wb-uploads.s3.amazonaws.com/public/1736934151835-about-us-hero-side-img.png',
    linkedin: 'linkedin.com/profile',
    facebook: null,
    instagram: null,
    website: null,
    email: 'amirsuliman10101@gmail.com',
    phoneNumber: '03478663296',
    workPhone: '121212121',
    reportingManagerId: 10,
    departmentId: 5,
    salary: 2444440,
    locationId: 1,
    effectiveDate: '2025-01-10T00:00:00.000Z',
    hireDate: '2025-01-09T00:00:00.000Z',
    birthday: '2025-01-09T00:00:00.000Z',
    userId: 4,
    manager: {
      firstName: 'testing',
      lastName: 'user',
      department: {
        id: 1,
        name: 'Engineering',
        employeeId: '',
      },
      location: {
        id: 1,
        street1: '1365',
        street2: null,
        zipCode: 23000,
        city: 'Prishtine',
        country: 'Albania',
        state: 'Kosovo',
      },
    },
    location: {
      country: 'Albania',
      state: 'Kosovo',
      city: 'Prishtine',
      zipCode: 23000,
      id: 1,
      street1: '1365',
      street2: null,
    },
    department: {
      id: 1,
      name: 'Finance',
    },
    openPositions: [],
    parentId: 2,
  },
  {
    id: 4,
    firstName: 'Amir',
    middleName: '',
    lastName: 'Suliman',
    tittle: 'Front-end Developer',
    gender: 'Male',
    marritialStatus: 'Single',
    paymentSchedule: 'Biweekly',
    employmentType: 'Freelance',
    profilePictureUrl:
      'https://wb-uploads.s3.amazonaws.com/public/1736934151835-about-us-hero-side-img.png',
    linkedin: 'linkedin.com/profile',
    facebook: null,
    instagram: null,
    website: null,
    email: 'amirsuliman10101@gmail.com',
    phoneNumber: '03478663296',
    workPhone: '121212121',
    reportingManagerId: 10,
    departmentId: 5,
    salary: 2444440,
    locationId: 1,
    effectiveDate: '2025-01-10T00:00:00.000Z',
    hireDate: '2025-01-09T00:00:00.000Z',
    birthday: '2025-01-09T00:00:00.000Z',
    userId: 4,
    manager: {
      firstName: 'testing',
      lastName: 'user',
      department: {
        id: 1,
        name: 'Engineering',
        employeeId: '',
      },
      location: {
        id: 1,
        street1: '1365',
        street2: null,
        zipCode: 23000,
        city: 'Prishtine',
        country: 'Albania',
        state: 'Kosovo',
      },
    },
    location: {
      country: 'Albania',
      state: 'Kosovo',
      city: 'Prishtine',
      zipCode: 23000,
      id: 1,
      street1: '1365',
      street2: null,
    },
    department: {
      id: 1,
      name: 'Finance',
    },
    openPositions: [],
    parentId: 2,
  },
];

// export const orgChartData = [
//   {
//     id: 3,
//     firstName: 'Ervin',
//     middleName: null,
//     lastName: 'Mrishaj',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: '',
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'ervin.mrishaj@isaconsulting.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: null,
//     departmentId: 2,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 2,
//     manager: null,
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Marketing',
//     },
//     openPositions: [
//       {
//         id: 5,
//         tittle: 'Sales Representative',
//         departmentId: 3,
//         salary: 45000,
//         department: {
//           id: 3,
//           name: 'Sales',
//         },
//         location: {
//           id: 16,
//           street1: 'Commerce Boulevard',
//           street2: null,
//           zipCode: '75201',
//           city: 'Dallas',
//           country: 'USA',
//           state: 'Texas',
//         },
//       },
//       {
//         id: 6,
//         tittle: 'Sales Representative',
//         departmentId: 3,
//         salary: 45000,
//         department: {
//           id: 3,
//           name: 'Sales',
//         },
//         location: {
//           id: 17,
//           street1: 'Commerce Boulevard',
//           street2: null,
//           zipCode: '75201',
//           city: 'Dallas',
//           country: 'USA',
//           state: 'Texas',
//         },
//       },
//       {
//         id: 7,
//         tittle: 'Sales Representative',
//         departmentId: 3,
//         salary: 45000,
//         department: {
//           id: 3,
//           name: 'Sales',
//         },
//         location: {
//           id: 18,
//           street1: 'Commerce Boulevard',
//           street2: null,
//           zipCode: '75201',
//           city: 'Dallas',
//           country: 'USA',
//           state: 'Texas',
//         },
//       },
//     ],
//     parentId: null,
//   },
//   {
//     id: 2,
//     firstName: 'Super',
//     middleName: null,
//     lastName: 'Admin',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: 'Fulltime',
//     profilePictureUrl:
//       'https://wb-uploads.s3.amazonaws.com/public/1736925376860-ISA_Logo_black.png',
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'dc_superadmin@isa.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 7,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: '2025-01-01T00:00:00.000Z',
//     hireDate: '2025-01-01T00:00:00.000Z',
//     birthday: '2000-01-01T00:00:00.000Z',
//     userId: 1,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'IT',
//     },
//     openPositions: [
//       {
//         id: 9,
//         tittle: 'Front-end developer',
//         departmentId: 1,
//         salary: 3000,
//         department: {
//           id: 1,
//           name: 'Engineering',
//         },
//         location: {
//           id: 22,
//           street1: 'Kabal Swat',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//       {
//         id: 10,
//         tittle: 'Software Engineer',
//         departmentId: 1,
//         salary: 3000,
//         department: {
//           id: 1,
//           name: 'Engineering',
//         },
//         location: {
//           id: 23,
//           street1: 'Kabal Swat',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//       {
//         id: 19,
//         tittle: 'Updated Job tittle',
//         departmentId: 3,
//         salary: 60000,
//         department: {
//           id: 3,
//           name: 'Sales',
//         },
//         location: {
//           id: 50,
//           street1: 'Updated street',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//       {
//         id: 20,
//         tittle: 'Updated Job tittle',
//         departmentId: 3,
//         salary: 60000,
//         department: {
//           id: 3,
//           name: 'Sales',
//         },
//         location: {
//           id: 51,
//           street1: 'Updated street',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//       {
//         id: 22,
//         tittle: 'QA',
//         departmentId: 3,
//         salary: 1234,
//         department: {
//           id: 3,
//           name: 'Sales',
//         },
//         location: {
//           id: 59,
//           street1: 'street',
//           street2: '',
//           zipCode: '10000',
//           city: 'city',
//           country: 'country',
//           state: 'state',
//         },
//       },
//     ],
//     parentId: 3,
//   },
//   {
//     id: 37,
//     firstName: 'John',
//     middleName: null,
//     lastName: 'Doe',
//     tittle: 'HR',
//     gender: null,
//     marritialStatus: null,
//     paymentSchedule: null,
//     employmentType: 'Fulltime',
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'email@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 4,
//     salary: 0,
//     locationId: null,
//     effectiveDate: null,
//     hireDate: null,
//     birthday: null,
//     userId: 47,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Human Resources',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 36,
//     firstName: 'John',
//     middleName: '',
//     lastName: 'Doe',
//     tittle: 'HR',
//     gender: 'Male',
//     marritialStatus: 'Prefer not say',
//     paymentSchedule: 'Once a month',
//     employmentType: 'Fulltime',
//     profilePictureUrl:
//       'https://wb-uploads.s3.amazonaws.com/public/1737705104439-about2.png',
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'someemail@gmail.com',
//     phoneNumber: '21312132',
//     workPhone: '312123',
//     reportingManagerId: 3,
//     departmentId: 10,
//     salary: 1,
//     locationId: 65,
//     effectiveDate: '2025-01-01T00:00:00.000Z',
//     hireDate: '2024-12-30T00:00:00.000Z',
//     birthday: '2018-06-24T00:00:00.000Z',
//     userId: 46,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'asdas',
//       state: 'dad aad',
//       city: 'dasdas',
//       zipcode: '23122',
//     },
//     department: {
//       name: 'ahahahha',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 35,
//     firstName: 'John',
//     middleName: null,
//     lastName: 'Doe',
//     tittle: 'HR',
//     gender: null,
//     marritialStatus: null,
//     paymentSchedule: null,
//     employmentType: 'Fulltime',
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'superadmin@domain.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 4,
//     salary: 0,
//     locationId: null,
//     effectiveDate: null,
//     hireDate: null,
//     birthday: null,
//     userId: 45,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Human Resources',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 33,
//     firstName: 'Abc',
//     middleName: null,
//     lastName: 'xyz',
//     tittle: 'Some job title',
//     gender: 'Male',
//     marritialStatus: 'Enganged',
//     paymentSchedule: 'Once a month',
//     employmentType: 'Fulltime',
//     profilePictureUrl: null,
//     linkedin: '',
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'abc@gmail.com',
//     phoneNumber: '12312312',
//     workPhone: '123123',
//     reportingManagerId: 3,
//     departmentId: 10,
//     salary: 1213,
//     locationId: 61,
//     effectiveDate: '2025-02-12T00:00:00.000Z',
//     hireDate: '2024-02-10T00:00:00.000Z',
//     birthday: '1990-02-12T00:00:00.000Z',
//     userId: 43,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Tirana',
//       zipcode: '1234',
//     },
//     department: {
//       name: 'ahahahha',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 32,
//     firstName: 'Ida',
//     middleName: null,
//     lastName: 'Besimaj',
//     tittle: 'HR',
//     gender: null,
//     marritialStatus: null,
//     paymentSchedule: null,
//     employmentType: 'Fulltime',
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'idabesimi@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 4,
//     salary: 0,
//     locationId: null,
//     effectiveDate: null,
//     hireDate: null,
//     birthday: null,
//     userId: 42,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Human Resources',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 30,
//     firstName: 'Test',
//     middleName: null,
//     lastName: 'Test',
//     tittle: 'HR',
//     gender: null,
//     marritialStatus: null,
//     paymentSchedule: null,
//     employmentType: 'Fulltime',
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'monnygegaj+1@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 4,
//     salary: 0,
//     locationId: null,
//     effectiveDate: null,
//     hireDate: null,
//     birthday: null,
//     userId: 40,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Human Resources',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 26,
//     firstName: 'John',
//     middleName: null,
//     lastName: 'Doe',
//     tittle: 'HR',
//     gender: null,
//     marritialStatus: null,
//     paymentSchedule: null,
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'ranar48916@nozamas.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 4,
//     salary: 0,
//     locationId: null,
//     effectiveDate: null,
//     hireDate: null,
//     birthday: null,
//     userId: 34,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Human Resources',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 25,
//     firstName: 'Frida',
//     middleName: null,
//     lastName: 'Besimaj',
//     tittle: 'HR',
//     gender: null,
//     marritialStatus: null,
//     paymentSchedule: null,
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'frida.besimaj@isaconsulting.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 4,
//     salary: 0,
//     locationId: null,
//     effectiveDate: null,
//     hireDate: null,
//     birthday: null,
//     userId: 33,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Human Resources',
//     },
//     openPositions: [
//       {
//         id: 21,
//         tittle: 'SQA Engineer',
//         departmentId: 3,
//         salary: 33400,
//         department: {
//           id: 3,
//           name: 'Sales',
//         },
//         location: {
//           id: 56,
//           street1: 'isa street',
//           street2: 'another street',
//           zipCode: '1234',
//           city: 'My city',
//           country: 'USA',
//           state: 'Kosova',
//         },
//       },
//     ],
//     parentId: 3,
//   },
//   {
//     id: 24,
//     firstName: 'ABDUL',
//     middleName: null,
//     lastName: 'MAJID',
//     tittle: 'HR',
//     gender: null,
//     marritialStatus: null,
//     paymentSchedule: null,
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'abdulmajid1m1@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 4,
//     salary: 0,
//     locationId: null,
//     effectiveDate: null,
//     hireDate: null,
//     birthday: null,
//     userId: 32,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Human Resources',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 22,
//     firstName: 'testing',
//     middleName: null,
//     lastName: 'user',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'test4@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 23,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 20,
//     firstName: 'ABDUL',
//     middleName: null,
//     lastName: 'MAJID',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'abdulmajid1m2@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 21,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 18,
//     firstName: 'again',
//     middleName: null,
//     lastName: 'tesrting',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'again@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 19,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 17,
//     firstName: 'hr',
//     middleName: null,
//     lastName: 'tesing3',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'hrtesting3@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 18,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 15,
//     firstName: 'hr',
//     middleName: null,
//     lastName: 'two',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'hrtwo@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 16,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 5,
//     firstName: 'Chris',
//     middleName: '',
//     lastName: 'User',
//     tittle: 'Employee',
//     gender: 'Male',
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: 'Fulltime',
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'testing@isa.com',
//     phoneNumber: '01234',
//     workPhone: '049211515',
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 2000,
//     locationId: 1,
//     effectiveDate: '2024-04-15T00:00:00.000Z',
//     hireDate: '2024-11-15T00:00:00.000Z',
//     birthday: null,
//     userId: 5,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [
//       {
//         id: 2,
//         tittle: 'Marketing Specialist',
//         departmentId: 4,
//         salary: 50000,
//         department: {
//           id: 4,
//           name: 'Human Resources',
//         },
//         location: {
//           id: 5,
//           street1: 'Market Street',
//           street2: 'Suite 203',
//           zipCode: '94103',
//           city: 'San Francisco',
//           country: 'USA',
//           state: 'California',
//         },
//       },
//     ],
//     parentId: 3,
//   },
//   {
//     id: 6,
//     firstName: 'Role 1',
//     middleName: null,
//     lastName: 'User1',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'testing1@isa.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 6,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 7,
//     firstName: 'Testing',
//     middleName: null,
//     lastName: 'Reset',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'hasnain.dev.98@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 2,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 7,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Marketing',
//     },
//     openPositions: [
//       {
//         id: 13,
//         tittle: 'Senior Frontend Developer',
//         departmentId: 5,
//         salary: 3000,
//         department: {
//           id: 5,
//           name: 'Finance',
//         },
//         location: {
//           id: 36,
//           street1: 'Kabal Swat',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//       {
//         id: 14,
//         tittle: 'Senior Frontend Developer',
//         departmentId: 5,
//         salary: 3000,
//         department: {
//           id: 5,
//           name: 'Finance',
//         },
//         location: {
//           id: 37,
//           street1: 'Kabal Swat',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//       {
//         id: 15,
//         tittle: 'Senior Frontend Developer',
//         departmentId: 5,
//         salary: 3000,
//         department: {
//           id: 5,
//           name: 'Finance',
//         },
//         location: {
//           id: 38,
//           street1: 'Kabal Swat',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//       {
//         id: 16,
//         tittle: 'Senior Frontend Developer',
//         departmentId: 5,
//         salary: 3000,
//         department: {
//           id: 5,
//           name: 'Finance',
//         },
//         location: {
//           id: 39,
//           street1: 'Kabal Swat',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//       {
//         id: 17,
//         tittle: 'Senior Frontend Developer',
//         departmentId: 5,
//         salary: 3000,
//         department: {
//           id: 5,
//           name: 'Finance',
//         },
//         location: {
//           id: 40,
//           street1: 'Kabal Swat',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//       {
//         id: 18,
//         tittle: 'Senior Frontend Developer',
//         departmentId: 5,
//         salary: 3000,
//         department: {
//           id: 5,
//           name: 'Finance',
//         },
//         location: {
//           id: 41,
//           street1: 'Kabal Swat',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//     ],
//     parentId: 3,
//   },
//   {
//     id: 8,
//     firstName: 'Moni',
//     middleName: null,
//     lastName: 'Gega',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'a.gegaj8@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 9,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 9,
//     firstName: 'Abdul',
//     middleName: null,
//     lastName: 'Majid',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: 'https://www.google.com',
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'abdul.majid@isaconsulting.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 2,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 10,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Marketing',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 10,
//     firstName: 'testing',
//     middleName: null,
//     lastName: 'user',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'testing2@isa.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 11,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 12,
//     firstName: 'testing',
//     middleName: null,
//     lastName: 'user',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'user@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 13,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 13,
//     firstName: 'testing3',
//     middleName: null,
//     lastName: 'user',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'testing3@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 14,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [
//       {
//         id: 12,
//         tittle: 'Senior Frontend Developer',
//         departmentId: 2,
//         salary: 3000,
//         department: {
//           id: 2,
//           name: 'Marketing',
//         },
//         location: {
//           id: 35,
//           street1: 'Kabal Swat',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//     ],
//     parentId: 3,
//   },
//   {
//     id: 14,
//     firstName: 'Hr ',
//     middleName: null,
//     lastName: 'Testing',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'hrtesting@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 15,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 11,
//     firstName: 'testing',
//     middleName: null,
//     lastName: 'user',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'testing@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 12,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [
//       {
//         id: 3,
//         tittle: 'Graphic Designer',
//         departmentId: 6,
//         salary: 45000,
//         department: {
//           id: 6,
//           name: 'Department name',
//         },
//         location: {
//           id: 9,
//           street1: 'Creative Street',
//           street2: null,
//           zipCode: '75001',
//           city: 'Dallas',
//           country: 'USA',
//           state: 'Texas',
//         },
//       },
//     ],
//     parentId: 3,
//   },
//   {
//     id: 16,
//     firstName: 'Ubaid',
//     middleName: null,
//     lastName: 'Khan',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'ubaiduu647@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 3,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 17,
//     manager: {
//       firstName: 'Ervin',
//       lastName: 'Mrishaj',
//       department: {
//         id: 2,
//         name: 'Marketing',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 23,
//     firstName: 'Amir',
//     middleName: null,
//     lastName: 'Suliman',
//     tittle: 'HR',
//     gender: null,
//     marritialStatus: null,
//     paymentSchedule: null,
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'amir.suliman@isaconsulting.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 4,
//     departmentId: 4,
//     salary: 0,
//     locationId: null,
//     effectiveDate: null,
//     hireDate: null,
//     birthday: null,
//     userId: 31,
//     manager: {
//       firstName: 'Amir',
//       lastName: 'Suliman',
//       department: {
//         id: 7,
//         name: 'IT',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Human Resources',
//     },
//     openPositions: [],
//     parentId: 3,
//   },
//   {
//     id: 27,
//     firstName: 'Jhon',
//     middleName: '',
//     lastName: 'Doe',
//     tittle: 'Senior Frontend Developer',
//     gender: 'Male',
//     marritialStatus: 'Enganged',
//     paymentSchedule: 'Weekly',
//     employmentType: 'Freelance',
//     profilePictureUrl:
//       'blob:http://localhost:3000/830a42fa-86da-42d6-bc44-16c908a26c5b',
//     linkedin: 'https://linkedin.com',
//     facebook: 'https://facebook.com',
//     instagram: 'https://instagram.com',
//     website: '',
//     email: 'amir1@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 4,
//     departmentId: 1,
//     salary: 3000,
//     locationId: null,
//     effectiveDate: '2024-11-25T00:00:00.000Z',
//     hireDate: null,
//     birthday: '2024-11-25T00:00:00.000Z',
//     userId: 35,
//     manager: {
//       firstName: 'Amir',
//       lastName: 'Suliman',
//       department: {
//         id: 7,
//         name: 'IT',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 4,
//   },
//   {
//     id: 29,
//     firstName: 'Gresa',
//     middleName: '',
//     lastName: 'Baruti',
//     tittle: 'QA',
//     gender: 'Female',
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: 'Part Time',
//     profilePictureUrl: null,
//     linkedin: '',
//     facebook: '',
//     instagram: '',
//     website: '',
//     email: 'gresabaruti1@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 4,
//     departmentId: 1,
//     salary: 1500,
//     locationId: null,
//     effectiveDate: '2024-01-01T00:00:00.000Z',
//     hireDate: null,
//     birthday: '1994-04-30T00:00:00.000Z',
//     userId: 38,
//     manager: {
//       firstName: 'Amir',
//       lastName: 'Suliman',
//       department: {
//         id: 7,
//         name: 'IT',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 4,
//   },
//   {
//     id: 19,
//     firstName: 'test4',
//     middleName: null,
//     lastName: 'user',
//     tittle: 'Employee',
//     gender: null,
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: null,
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'testing4@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 4,
//     departmentId: 1,
//     salary: 3000,
//     locationId: 1,
//     effectiveDate: null,
//     hireDate: '2024-11-19T10:40:56.000Z',
//     birthday: null,
//     userId: 20,
//     manager: {
//       firstName: 'Amir',
//       lastName: 'Suliman',
//       department: {
//         id: 7,
//         name: 'IT',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 4,
//   },
//   {
//     id: 1,
//     firstName: 'John',
//     middleName: '',
//     lastName: 'Doe',
//     tittle: 'Developer',
//     gender: 'Male',
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: 'Fulltime',
//     profilePictureUrl: null,
//     linkedin: 'linkedin.com/profile',
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'johny@gmail.com',
//     phoneNumber: '',
//     workPhone: '',
//     reportingManagerId: 4,
//     departmentId: 3,
//     salary: 2444440,
//     locationId: 1,
//     effectiveDate: '2024-04-15T00:00:00.000Z',
//     hireDate: '2024-04-15T00:00:00.000Z',
//     birthday: '2020-04-15T00:00:00.000Z',
//     userId: 3,
//     manager: {
//       firstName: 'Amir',
//       lastName: 'Suliman',
//       department: {
//         id: 7,
//         name: 'IT',
//         employeeId: '',
//       },
//       location: {
//         id: 1,
//         street1: '1365',
//         street2: null,
//         zipCode: '23000',
//         city: 'Prishtine',
//         country: 'Albania',
//         state: 'Kosovo',
//       },
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'Sales',
//     },
//     openPositions: [
//       {
//         id: 1,
//         tittle: 'Job tittle',
//         departmentId: 1,
//         salary: 60000,
//         department: {
//           id: 1,
//           name: 'Engineering',
//         },
//         location: {
//           id: 2,
//           street1: 'Street',
//           street2: null,
//           zipCode: '23000',
//           city: 'Prishtine',
//           country: 'Albania',
//           state: 'Kosovo',
//         },
//       },
//       {
//         id: 4,
//         tittle: 'Product Manager',
//         departmentId: 1,
//         salary: 120000,
//         department: {
//           id: 1,
//           name: 'Engineering',
//         },
//         location: {
//           id: 14,
//           street1: 'Innovation Street',
//           street2: 'Suite 5A',
//           zipCode: '94016',
//           city: 'San Mateo',
//           country: 'USA',
//           state: 'California',
//         },
//       },
//       {
//         id: 8,
//         tittle: 'Front-end developer',
//         departmentId: 2,
//         salary: 3000,
//         department: {
//           id: 2,
//           name: 'Marketing',
//         },
//         location: {
//           id: 20,
//           street1: 'Kabal Swat',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Swat',
//         },
//       },
//       {
//         id: 11,
//         tittle: 'Senior Frontend Developer',
//         departmentId: 1,
//         salary: 3000,
//         department: {
//           id: 1,
//           name: 'Engineering',
//         },
//         location: {
//           id: 24,
//           street1: 'Kabal Swat',
//           street2: 'Green Iqbal Plaza',
//           zipCode: '19060',
//           city: 'Mingora',
//           country: 'Pakistan',
//           state: 'Mingora',
//         },
//       },
//       {
//         id: 23,
//         tittle: 'Job tittle',
//         departmentId: 1,
//         salary: 60000,
//         department: {
//           id: 1,
//           name: 'Engineering',
//         },
//         location: {
//           id: 60,
//           street1: 'Street',
//           street2: null,
//           zipCode: '23000',
//           city: 'Prishtine',
//           country: 'Albania',
//           state: 'Kosovo',
//         },
//       },
//     ],
//     parentId: 4,
//   },
//   {
//     id: 4,
//     firstName: 'Amir',
//     middleName: '',
//     lastName: 'Suliman',
//     tittle: 'Front-end Developer',
//     gender: 'Male',
//     marritialStatus: 'Single',
//     paymentSchedule: 'Biweekly',
//     employmentType: 'Freelance',
//     profilePictureUrl:
//       'https://wb-uploads.s3.amazonaws.com/public/1736934151835-about-us-hero-side-img.png',
//     linkedin: 'https://linkedin.com/profile',
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'amirsuliman10101@gmail.com',
//     phoneNumber: '3478663296',
//     workPhone: '121212121',
//     reportingManagerId: 23,
//     departmentId: 7,
//     salary: 2444440,
//     locationId: 1,
//     effectiveDate: '2025-01-10T00:00:00.000Z',
//     hireDate: '2025-01-09T00:00:00.000Z',
//     birthday: '2025-01-09T00:00:00.000Z',
//     userId: 4,
//     manager: {
//       firstName: 'Amir',
//       lastName: 'Suliman',
//       department: {
//         id: 4,
//         name: 'Human Resources',
//         employeeId: '',
//       },
//       location: null,
//     },
//     location: {
//       country: 'Albania',
//       state: 'Kosovo',
//       city: 'Prishtine',
//       zipcode: '23000',
//     },
//     department: {
//       name: 'IT',
//     },
//     openPositions: [],
//     parentId: 23,
//   },
//   {
//     id: 42,
//     firstName: 'New ',
//     middleName: '',
//     lastName: 'user',
//     tittle: 'Orater',
//     gender: 'Male',
//     marritialStatus: 'Prefer not say',
//     paymentSchedule: 'Biweekly',
//     employmentType: 'Part Time',
//     profilePictureUrl:
//       'blob:http://localhost:3000/a145ce9f-211b-4987-8e95-2c1f7ccce1e8',
//     linkedin: '',
//     facebook: '',
//     instagram: '',
//     website: '',
//     email: 'ag@gmail.com',
//     phoneNumber: '932840984',
//     workPhone: '2908409823',
//     reportingManagerId: 36,
//     departmentId: 8,
//     salary: 3000,
//     locationId: 66,
//     effectiveDate: '2025-01-23T00:00:00.000Z',
//     hireDate: '2025-01-15T00:00:00.000Z',
//     birthday: '2024-12-31T00:00:00.000Z',
//     userId: 52,
//     manager: {
//       firstName: 'John',
//       lastName: 'Doe',
//       department: {
//         id: 10,
//         name: 'ahahahha',
//         employeeId: '',
//       },
//       location: {
//         id: 65,
//         street1: 'asdda',
//         street2: null,
//         zipCode: '23122',
//         city: 'dasdas',
//         country: 'asdas',
//         state: 'dad aad',
//       },
//     },
//     location: {
//       country: 'jflskjdf',
//       state: 'fsfksjfl',
//       city: 'dsfjl',
//       zipcode: '987987',
//     },
//     department: {
//       name: 'AI',
//     },
//     openPositions: [],
//     parentId: 36,
//   },
//   {
//     id: 41,
//     firstName: 'Validated ',
//     middleName: '',
//     lastName: 'User',
//     tittle: 'Astronaute',
//     gender: 'Male',
//     marritialStatus: 'Enganged',
//     paymentSchedule: 'Once a month',
//     employmentType: 'Part Time',
//     profilePictureUrl: null,
//     linkedin: '',
//     facebook: '',
//     instagram: '',
//     website: '',
//     email: 'a@g.com',
//     phoneNumber: '213123123',
//     workPhone: '31321',
//     reportingManagerId: 36,
//     departmentId: 15,
//     salary: 1,
//     locationId: 64,
//     effectiveDate: '2025-01-02T00:00:00.000Z',
//     hireDate: '2025-01-01T00:00:00.000Z',
//     birthday: '2000-02-02T00:00:00.000Z',
//     userId: 51,
//     manager: {
//       firstName: 'John',
//       lastName: 'Doe',
//       department: {
//         id: 10,
//         name: 'ahahahha',
//         employeeId: '',
//       },
//       location: {
//         id: 65,
//         street1: 'asdda',
//         street2: null,
//         zipCode: '23122',
//         city: 'dasdas',
//         country: 'asdas',
//         state: 'dad aad',
//       },
//     },
//     location: {
//       country: 'space',
//       state: 'spaceship',
//       city: 'flight',
//       zipcode: '2222',
//     },
//     department: {
//       name: 'Shell',
//     },
//     openPositions: [],
//     parentId: 36,
//   },
//   {
//     id: 40,
//     firstName: 'FirstName',
//     middleName: 'MiddleName',
//     lastName: 'LastName',
//     tittle: 'QA',
//     gender: 'Female',
//     marritialStatus: 'Single',
//     paymentSchedule: 'Once a month',
//     employmentType: 'Fulltime',
//     profilePictureUrl:
//       'blob:https://workbridge-orcin.vercel.app/e63d82c6-9406-422c-8d17-77a5133a21a8',
//     linkedin: '',
//     facebook: '',
//     instagram: '',
//     website: '',
//     email: 'email@someemail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 36,
//     departmentId: 1,
//     salary: 1234,
//     locationId: null,
//     effectiveDate: '2024-01-01T00:00:00.000Z',
//     hireDate: null,
//     birthday: '1994-04-30T00:00:00.000Z',
//     userId: 50,
//     manager: {
//       firstName: 'John',
//       lastName: 'Doe',
//       department: {
//         id: 10,
//         name: 'ahahahha',
//         employeeId: '',
//       },
//       location: {
//         id: 65,
//         street1: 'asdda',
//         street2: null,
//         zipCode: '23122',
//         city: 'dasdas',
//         country: 'asdas',
//         state: 'dad aad',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 36,
//   },
//   {
//     id: 39,
//     firstName: 'Xyz',
//     middleName: '',
//     lastName: 'abc',
//     tittle: 'Engineer',
//     gender: 'Male',
//     marritialStatus: 'Married',
//     paymentSchedule: 'Weekly',
//     employmentType: 'Freelance',
//     profilePictureUrl:
//       'blob:http://localhost:3000/ed180d91-7664-41b5-b0f0-8db8d70fbf96',
//     linkedin: '',
//     facebook: '',
//     instagram: '',
//     website: '',
//     email: 'abcd@gmail.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 36,
//     departmentId: 1,
//     salary: 100000,
//     locationId: null,
//     effectiveDate: '2025-01-01T00:00:00.000Z',
//     hireDate: null,
//     birthday: '2000-10-10T00:00:00.000Z',
//     userId: 49,
//     manager: {
//       firstName: 'John',
//       lastName: 'Doe',
//       department: {
//         id: 10,
//         name: 'ahahahha',
//         employeeId: '',
//       },
//       location: {
//         id: 65,
//         street1: 'asdda',
//         street2: null,
//         zipCode: '23122',
//         city: 'dasdas',
//         country: 'asdas',
//         state: 'dad aad',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Engineering',
//     },
//     openPositions: [],
//     parentId: 36,
//   },
//   {
//     id: 38,
//     firstName: 'Imran ',
//     middleName: '',
//     lastName: 'Khan',
//     tittle: 'Marketing specialist',
//     gender: 'Male',
//     marritialStatus: 'Prefer not say',
//     paymentSchedule: 'Biweekly',
//     employmentType: 'Freelance',
//     profilePictureUrl:
//       'https://wb-uploads.s3.amazonaws.com/public/1737098067760-2149241242.jpg',
//     linkedin: '',
//     facebook: '',
//     instagram: '',
//     website: '',
//     email: 'imran@gmail.com',
//     phoneNumber: '27498734',
//     workPhone: '28737432',
//     reportingManagerId: 36,
//     departmentId: 14,
//     salary: 100000,
//     locationId: 63,
//     effectiveDate: '2025-01-01T00:00:00.000Z',
//     hireDate: '2025-01-01T00:00:00.000Z',
//     birthday: '1990-09-01T00:00:00.000Z',
//     userId: 48,
//     manager: {
//       firstName: 'John',
//       lastName: 'Doe',
//       department: {
//         id: 10,
//         name: 'ahahahha',
//         employeeId: '',
//       },
//       location: {
//         id: 65,
//         street1: 'asdda',
//         street2: null,
//         zipCode: '23122',
//         city: 'dasdas',
//         country: 'asdas',
//         state: 'dad aad',
//       },
//     },
//     location: {
//       country: 'Pakistan',
//       state: 'sdf',
//       city: 'Swat',
//       zipcode: '19060',
//     },
//     department: {
//       name: 'Dcse',
//     },
//     openPositions: [],
//     parentId: 36,
//   },
//   {
//     id: 34,
//     firstName: 'John',
//     middleName: null,
//     lastName: 'Doe',
//     tittle: 'HR',
//     gender: null,
//     marritialStatus: null,
//     paymentSchedule: null,
//     employmentType: 'Fulltime',
//     profilePictureUrl: null,
//     linkedin: null,
//     facebook: null,
//     instagram: null,
//     website: null,
//     email: 'someemail@domain.com',
//     phoneNumber: null,
//     workPhone: null,
//     reportingManagerId: 36,
//     departmentId: 4,
//     salary: 0,
//     locationId: null,
//     effectiveDate: null,
//     hireDate: null,
//     birthday: null,
//     userId: 44,
//     manager: {
//       firstName: 'John',
//       lastName: 'Doe',
//       department: {
//         id: 10,
//         name: 'ahahahha',
//         employeeId: '',
//       },
//       location: {
//         id: 65,
//         street1: 'asdda',
//         street2: null,
//         zipCode: '23122',
//         city: 'dasdas',
//         country: 'asdas',
//         state: 'dad aad',
//       },
//     },
//     location: null,
//     department: {
//       name: 'Human Resources',
//     },
//     openPositions: [],
//     parentId: 36,
//   },
// ];
